
services:
  mongodb:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ADMIN_PASSWORD}
    networks:
      - app_network
    ports:
      - 27017:27017

  mongo-express:
    container_name: db_admin
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_ADMIN_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_DB_ADMIN_USERNAME}:${MONGO_DB_ADMIN_PASSWORD}@mongo:27017
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - app_network

  # app:
  #   container_name: app
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   env_file: .env
  #   volumes:
  #     - ./app:/app
  #   depends_on:
  #     - mongodb
  #   environment:
  #     - MONGODB_URI=mongodb://${MONGO_DB_ADMIN_USERNAME}:${MONGO_DB_ADMIN_PASSWORD}@mongodb:27017
  #     - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
  #     - LANGUAGE_FILE_EN=${LANGUAGE_FILE_EN}
  #     - LANGUAGE_FILE_DE=${LANGUAGE_FILE_DE}
  #     - LANGUAGE_FILE_RU=${LANGUAGE_FILE_RU}
  #   networks:
  #     - app_network

  # parser:
  #   container_name: parser
  #   build:
  #     context: ./parser
  #     dockerfile: Dockerfile
  #   env_file: .env
  #   volumes:
  #     - ./parser:/app
  #   depends_on:
  #     - mongodb
  #   environment:
  #     - MONGODB_URI=mongodb://${MONGO_DB_ADMIN_USERNAME}:${MONGO_DB_ADMIN_PASSWORD}@mongodb:27017
  #   networks:
  #     - app_network

  # telegram_bot:
  #   container_name: tg_bot
  #   build:
  #     context: ./app/tg_bot
  #     dockerfile: Dockerfile
  #   env_file: .env
  #   volumes:
  #     - ./app/tg_bot:/app
  #   depends_on:
  #     - mongodb
  #   environment:
  #     - MONGODB_URI=mongodb://${MONGO_DB_ADMIN_USERNAME}:${MONGO_DB_ADMIN_PASSWORD}@mongodb:27017
  #     - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
  #     - LANGUAGE_FILE_EN=${LANGUAGE_FILE_EN}
  #     - LANGUAGE_FILE_DE=${LANGUAGE_FILE_DE}
  #     - LANGUAGE_FILE_RU=${LANGUAGE_FILE_RU}
  #   networks:
  #     - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
